## Задание 1

In [1]:
import numpy as np

In [5]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


## Задание 2

In [7]:
a.shape

(12,)

In [8]:
a1 = a.reshape(2, 6)
print(a1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [9]:
a2 = a.reshape(4, 3)
print(a2)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [10]:
a3 = a.reshape(12, 1)
print(a3)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [11]:
a4 = a.reshape(6, 2)
print(a4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [12]:
a5 = a.reshape(3, 4)
print(a5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Задание 3

In [13]:
a6 = a.reshape(2, -1)
print(a6)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [14]:
a7 = a.reshape(4, -1)
print(a7)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [15]:
a8 = a.reshape(12, -1)
print(a8)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [16]:
a9 = a.reshape(-1, 2)
print(a9)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [17]:
a10 = a.reshape(-1, 4)
print(a10)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Задание 4

In [112]:
print(a8.ndim)

2


In [ ]:
Массив Numpy, состоящий из одного столбца и 12 строк, нельзя назвать одномерным.

## Задание 5

In [116]:
b = np.random.randn(3, 4)
print(b)

[[-1.57415529  0.63795294 -2.04442302  1.06948089]
 [-0.93376284  0.78420819 -0.61487576  0.33289244]
 [-1.38071702 -0.28080629 -0.05981726  0.96117377]]


In [48]:
c = b.flatten()
print("Одомерный массив c: {}".format(c))
print("Размерность массива c: {}".format(c.ndim))
print("Форма массива c: {}".format(c.shape))

Одомерный массив c: [20 18 16 14 12 10  8  6  4  2]
Размерность массива c: 1
Форма массива c: (10,)


## Задание 6

In [45]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


## Задание 7

In [50]:
b = np.arange(20, 1, -2).reshape(1, 10)
print(b)
print("Размерность массива a: {}".format(a.ndim))
print("Размерность массива b: {}".format(b.ndim))
print("Форма массива a: {}".format(a.shape))
print("Форма массива b: {}".format(b.shape))

[[20 18 16 14 12 10  8  6  4  2]]
Размерность массива a: 1
Размерность массива b: 2
Форма массива a: (10,)
Форма массива b: (1, 10)


Так как по условию массив b состоит из одной строки и 10 столбцов, то он представляет собой двумерный массив в отличии от a, который является одномерным.

## Задание 8

In [55]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v)
print("Количество элементов массива v: {}".format(v.size))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Количество элементов массива v: 10


## Задание 9

In [56]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [59]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [61]:
d = np.linalg.det(B)

print("Определитель матрицы B: {}".format(d))
print("Размер матрицы B: {}".format(B.shape))

Определитель матрицы B: 0.0
Размер матрицы B: (4, 4)


Так как обратную матрицу можно посчитать только для матрицы, определитель которой не равен 0, то для матрицы B обратная матрица не определена.

## Задание 10

In [66]:
np.random.seed(42)

## Задание 11

In [94]:
c = np.random.randint(0, 16, (16,))
c

array([11, 14, 11,  6, 11, 12,  7, 14,  2, 13,  0,  3,  1,  7,  3,  1])

## Задание 12

In [97]:
C = c.reshape(4, 4)
print(C)

array([[11, 14, 11,  6],
       [11, 12,  7, 14],
       [ 2, 13,  0,  3],
       [ 1,  7,  3,  1]])

In [117]:
D = B + C * 10
print(D)

[[115 154 133  92]
 [124 170 156 262]
 [ 43 216 149 242]
 [ 42 192 242 312]]


In [104]:
print("Определитель матрицы D: {}".format(np.linalg.det(D)))
print("Ранг матрицы D: {}".format(np.linalg.matrix_rank(D)))

D_inv = np.linalg.inv(D)
print("Обратная матрица D_inv: {}".format(D_inv))

Определитель матрицы D: 292637600.0000002
Ранг матрицы D: 4
Обратная матрица D_inv: [[ 0.00301492  0.00842694 -0.00547886 -0.00371586]
 [ 0.00313685 -0.00491953  0.01099722 -0.00532372]
 [ 0.00624814 -0.00625634 -0.00825335  0.00981296]
 [-0.00718254  0.00674568  0.00037165 -0.00062986]]


## Задание 13

In [118]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
print(D_inv)

[[1. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]


In [111]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14  11   6]
 [ 14  12  86  14]
 [ 23  13   0 212]
 [  1 122 212   1]]
